name: Build & Push Artemis NodeJS App-A

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Get git SHA
      - name: Get git SHA short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and Publish Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          no-cache: true
          tags: |
            kanukhosla10/artemis-node-app-a:latest
            kanukhosla10/artemis-node-app-a:sha-${{ env.sha_short }}